// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DoseRight_2

#ifndef UI_WIFISCREEN_H
#define UI_WIFISCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiScreen
extern void ui_WifiScreen_screen_init(void);
extern void ui_WifiScreen_screen_destroy(void);
extern lv_obj_t * ui_WifiScreen;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

